core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('main_app.urls')),
    path('admin/', admin.site.urls),
]

main_app/urls.py
from django.urls import path
from . import views

app_name = 'main_app'
urlpatterns = [
    path('', views.index, name='index'),
    path('all_gpu_gigabyte/', views.all_gpu_gigabyte, name='all_gpu_gigabyte'),
    path('gpu_12gb_gigabyte/', views.gpu_12gb_gigabyte, name='gpu_12gb_gigabyte'),
    path('gpu_8gb_gigabyte/', views.gpu_8gb_gigabyte, name='gpu_8gb_gigabyte'),
    path('mb_gigabyte/', views.mb_gigabyte, name='mb_gigabyte'),
    path('top_gigabyte/', views.top_gigabyte, name='top_gigabyte'),
    path('top_asus/', views.top_asus, name='top_asus'),
    path('top_msi/', views.top_msi, name='top_msi'),
    path('all_gpu_msi/', views.all_gpu_msi, name='all_gpu_msi'),
    path('gpu_12gb_msi/', views.gpu_12gb_msi, name='gpu_12gb_msi'),
    path('gpu_8gb_msi/', views.gpu_8gb_msi, name='gpu_8gb_msi'),
    path('mb_msi/', views.mb_msi, name='mb_msi'),
    path('all_gpu_asus/', views.all_gpu_asus, name='all_gpu_asus'),
    path('gpu_12gb_asus/', views.gpu_12gb_asus, name='gpu_12gb_asus'),
    path('gpu_8gb_asus/', views.gpu_8gb_asus, name='gpu_8gb_asus'),
    path('mb_asus/', views.mb_asus, name='mb_asus'),
]

main_app/parser/models.py
from pydantic import BaseModel, field_validator
from typing import List, Optional

class Price(BaseModel):
    basic: int
    product: int
    total: int

    @field_validator('basic','product','total')
    def convert_price(cls, price: int) -> float:
        if price is not None:
            return price / 100

class SizeItem(BaseModel):
    price: Price


class Product(BaseModel):
    id: int
    brand: str
    rating: Optional[int] = None
    volume: int
    sizes: List[SizeItem]
    name: str

class Products(BaseModel):
    products: List[Product]

main_app/views.py
import time

from django.shortcuts import render
import csv
from .parser.parser import ParseVideocards

def read_csv_file():
    data = []
    with open('main_app/parser/wb_data.csv', mode='r', encoding='utf-8') as file:
        reader = csv.DictReader(file)
        for row in reader:
            data.append(row)
    return data

def all_gpu_asus(request):
    parser = ParseVideocards("https://www.wildberries.ru/brands/asus?sort=popular&page=1")
    parser.parse_all_videocards()
    data = read_csv_file()
    context = {
        'data': data,
        'category':'Видеокарты',
        'brand':'Asus'
    }
    return render(request, 'main_app/all_gpu.html', context)


def all_gpu_msi(request):
    parser = ParseVideocards("https://www.wildberries.ru/brands/msi?sort=popular&page=1")
    parser.parse_all_videocards()
    data = read_csv_file()
    context = {
        'data': data,
        'category':'Видеокарты',
        'brand':'MSI'
    }
    return render(request, 'main_app/all_gpu.html', context)


def all_gpu_gigabyte(request):
    parser = ParseVideocards("https://www.wildberries.ru/brands/gigabyte?sort=popular&page=1")
    parser.parse_all_videocards()
    data = read_csv_file()
    context = {
        'data': data,
        'category':'Видеокарты',
        'brand':'Gigabyte'
    }
    return render(request, 'main_app/all_gpu.html', context)


def gpu_12gb_gigabyte(request):
    parser = ParseVideocards("https://www.wildberries.ru/brands/gigabyte?sort=popular&page=1")
    parser.parse_12gb_videocard()
    data = read_csv_file()
    context = {
        'data': data,
        'category':'Видеокарты 12гб',
        'brand':'Gigabyte'
    }
    return render(request, 'main_app/all_gpu.html', context)


def gpu_12gb_asus(request):
    parser = ParseVideocards("https://www.wildberries.ru/brands/asus?sort=popular&page=1")
    parser.parse_12gb_videocard()
    data = read_csv_file()
    context = {
        'data': data,
        'category':'Видеокарты 12гб',
        'brand':'ASUS'
    }
    return render(request, 'main_app/all_gpu.html', context)


def gpu_12gb_msi(request):
    parser = ParseVideocards("https://www.wildberries.ru/brands/msi?sort=popular&page=1")
    parser.parse_12gb_videocard()
    data = read_csv_file()
    context = {
        'data': data,
        'category':'Видеокарты 12гб',
        'brand':'MSI'
    }
    return render(request, 'main_app/all_gpu.html', context)


def gpu_8gb_gigabyte(request):
    parser = ParseVideocards("https://www.wildberries.ru/brands/gigabyte?sort=popular&page=1")
    parser.parse_8gb_videocard()
    data = read_csv_file()
    context = {
        'data': data,
        'category':'Видеокарты 8гб',
        'brand':'Gigabyte'
    }
    return render(request, 'main_app/all_gpu.html', context)

def gpu_8gb_asus(request):
    parser = ParseVideocards("https://www.wildberries.ru/brands/asus?sort=popular&page=1")
    parser.parse_8gb_videocard()
    data = read_csv_file()
    context = {
        'data': data,
        'category':'Видеокарты 8гб',
        'brand':'ASUS'
    }
    return render(request, 'main_app/all_gpu.html', context)


def gpu_8gb_msi(request):
    parser = ParseVideocards("https://www.wildberries.ru/brands/msi?sort=popular&page=1")
    parser.parse_8gb_videocard()
    data = read_csv_file()
    context = {
        'data': data,
        'category':'Видеокарты 8гб',
        'brand':'MSI'
    }
    return render(request, 'main_app/all_gpu.html', context)


def mb_gigabyte(request):
    parser = ParseVideocards("https://www.wildberries.ru/brands/gigabyte?sort=popular&page=1")
    parser.parse_motherboards_ddr5()
    data = read_csv_file()
    context = {
        'data': data,
        'category':'Материнские платы на ddr5',
        'brand':'Gigabyte'
    }
    return render(request, 'main_app/all_gpu.html', context)

def mb_asus(request):
    parser = ParseVideocards("https://www.wildberries.ru/brands/asus?sort=popular&page=1")
    parser.parse_motherboards_ddr5()
    data = read_csv_file()
    context = {
        'data': data,
        'category':'Материнские платы на ddr5',
        'brand':'ASUS'
    }
    return render(request, 'main_app/all_gpu.html', context)

def mb_msi(request):
    parser = ParseVideocards("https://www.wildberries.ru/brands/msi?sort=popular&page=1")
    parser.parse_motherboards_ddr5()
    data = read_csv_file()
    context = {
        'data': data,
        'category':'Материнские платы на ddr5',
        'brand':'MSI'
    }
    return render(request, 'main_app/all_gpu.html', context)



def top_gigabyte(request):
    parser = ParseVideocards("https://www.wildberries.ru/brands/gigabyte?sort=popular&page=1")
    parser.parse_top_47()
    data = read_csv_file()
    context = {
        'data': data,
        'category':'Материнские платы на ddr5',
        'brand':'Gigabyte'
    }
    return render(request, 'main_app/all_gpu.html', context)

def top_asus(request):
    parser = ParseVideocards("https://www.wildberries.ru/brands/asus?sort=popular&page=1")
    parser.parse_top_47()
    data = read_csv_file()
    context = {
        'data': data,
        'category':'Материнские платы на ddr5',
        'brand':'ASUS'
    }
    return render(request, 'main_app/all_gpu.html', context)

def top_msi(request):
    parser = ParseVideocards("https://www.wildberries.ru/brands/msi?sort=popular&page=1")
    parser.parse_top_47()
    data = read_csv_file()
    context = {
        'data': data,
        'category':'Материнские платы на ddr5',
        'brand':'MSI'
    }
    return render(request, 'main_app/all_gpu.html', context)




def index(request):
    '''Домашняя страница.'''
    return render(request, 'main_app/index.html')

main_app/templates/main_app/all_gpu.html
{% extends "main_app/base.html" %}


{% block content %}
    <h1>{{category}} {{brand}}</h1>
    <table border="1">
        <tr>
            <th>ID</th>
            <th>Название</th>
            <th>Бренд</th>
            <th>Цена</th>
            <th>Скидка</th>
            <th>В наличии</th>
            <th>Рейтинг</th>
        </tr>
        {% for row in data %}
        <tr>
            <td>{{ row.id }}</td>
            <td>{{ row.название }}</td>
            <td>{{ row.бренд }}</td>
            <td>{{ row.цена }}</td>
            <td>{{ row.скидка }}</td>
            <td>{{ row.наличие }}</td>
            <td>{{ row.рейтинг }}</td>
        </tr>
        {% endfor %}
    </table>
{% endblock content %}

main_app/templates/main_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>WB PARS: DEMO</title>
    <style>
    </style>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/5.1.3/css/bootstrap.min.css" rel="stylesheet">
    {% load django_bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}

</head>
<body>
<nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'main_app:index' %}">
            WB PARS: DEMO</a>

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarCollapse" aria-controls="navbarCollapse"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav me-auto mb-2 mb-md-0">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'main_app:top_gigabyte' %}">
                        топ GIGABYTE</a></li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'main_app:top_msi' %}">
                        топ MSI</a></li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'main_app:top_asus' %}">
                        топ ASUS</a></li>
            </ul>
        </div>
    </div>
</nav>

<main class="container">
    {% block page_header %}

    {% endblock page_header %}

    {% block content %}
    {% endblock content %}
</main>

</body>
</html>

main_app/templates/main_app/index.html
{% extends "main_app/base.html" %}


{% block content %}
<br/>
<div style="width: 70%; margin: 0 auto; text-align: center;">
    <h6>Главная страница</h6>
    <div class="pb-1 mb-1 border-bottom"></div>
    <br/><br/>
    <h6>Видеокарты с WB</h6>
    <br/>
    <h6>GIGABYTE</h6>
    <a class="btn btn-outline-success btn-sm"
           href="{% url 'main_app:mb_gigabyte' %}">Мат.платы ddr5</a>
    <a class="btn btn-success btn-sm"
           href="{% url 'main_app:all_gpu_gigabyte' %}">Все видеокарты</a>
    <a class="btn btn-success btn-sm"
           href="{% url 'main_app:gpu_12gb_gigabyte' %}">12gb</a>
    <a class="btn btn-success btn-sm"
           href="{% url 'main_app:gpu_8gb_gigabyte' %}">8gb</a>
    <br/><br/>
    <h6>MSI</h6>
    <a class="btn btn-outline-danger btn-sm"
           href="{% url 'main_app:mb_msi' %}">Мат.платы ddr5</a>
    <a class="btn btn-danger btn-sm"
           href="{% url 'main_app:all_gpu_msi' %}">Все видеокарты</a>
    <a class="btn btn-danger btn-sm"
           href="{% url 'main_app:gpu_12gb_msi' %}">12gb</a>
    <a class="btn btn-danger btn-sm"
           href="{% url 'main_app:gpu_8gb_msi' %}">8gb</a>
    <br/><br/>
    <h6>ASUS</h6>
    <a class="btn btn-outline-warning btn-sm"
           href="{% url 'main_app:mb_asus' %}">Мат.платы ddr5</a>
    <a class="btn btn-warning btn-sm"
           href="{% url 'main_app:all_gpu_asus' %}">Все видеокарты</a>
    <a class="btn btn-warning btn-sm"
           href="{% url 'main_app:gpu_12gb_asus' %}">12gb</a>
    <a class="btn btn-warning btn-sm"
           href="{% url 'main_app:gpu_8gb_asus' %}">8gb</a>

</div>
<br/><br/><br/><br/><br/><br/>
{% endblock content %}